#if UNITY_IOS
using UnityEngine;
using UnityEditor;
using UnityEditor.Callbacks;
using UnityEditor.iOS.Xcode;
using System.IO;

namespace GoogleSignIn.Editor
{
    public class GoogleSignInPostProcess
    {
        [PostProcessBuild(1)]
        public static void OnPostProcessBuild(BuildTarget buildTarget, string path)
        {
            if (buildTarget != BuildTarget.iOS)
                return;

            string plistPath = Path.Combine(path, "Info.plist");
            PlistDocument plist = new PlistDocument();
            plist.ReadFromFile(plistPath);

            // Read REVERSED_CLIENT_ID from GoogleService-Info.plist
            string googleServiceInfoPath = Path.Combine(Application.dataPath, "GoogleService-Info.plist");
            string reversedClientId = null;

            if (File.Exists(googleServiceInfoPath))
            {
                PlistDocument googleServiceInfo = new PlistDocument();
                googleServiceInfo.ReadFromFile(googleServiceInfoPath);
                reversedClientId = googleServiceInfo.root["REVERSED_CLIENT_ID"].AsString();
            }

            // Add URL scheme if REVERSED_CLIENT_ID is found
            if (!string.IsNullOrEmpty(reversedClientId))
            {
                PlistElementArray urlTypes = plist.root.CreateArray("CFBundleURLTypes");
                PlistElementDict urlType = urlTypes.AddDict();
                PlistElementArray urlSchemes = urlType.CreateArray("CFBundleURLSchemes");
                urlSchemes.AddString(reversedClientId);

                Debug.Log($"[GoogleSignIn] Added URL scheme: {reversedClientId}");
            }
            else
            {
                Debug.LogWarning("[GoogleSignIn] REVERSED_CLIENT_ID not found in GoogleService-Info.plist. URL scheme not added.");
            }

            // Ensure GoogleService-Info.plist is copied to the build and added to Xcode project
            string sourcePlist = Path.Combine(Application.dataPath, "GoogleService-Info.plist");
            string destPlist = Path.Combine(path, "GoogleService-Info.plist");

            if (File.Exists(sourcePlist))
            {
                File.Copy(sourcePlist, destPlist, true);
                Debug.Log("[GoogleSignIn] Copied GoogleService-Info.plist to iOS build");
                
                // Add GoogleService-Info.plist to Xcode project so it's included in the bundle
                string projPath = Path.Combine(path, "Unity-iPhone.xcodeproj", "project.pbxproj");
                if (File.Exists(projPath))
                {
                    PBXProject project = new PBXProject();
                    project.ReadFromString(File.ReadAllText(projPath));
                    
                    string targetGuid = project.GetUnityMainTargetGuid();
                    
                    // Check if file already exists in project
                    string existingFileGuid = project.FindFileGuidByProjectPath("GoogleService-Info.plist");
                    string fileGuid;
                    
                    if (string.IsNullOrEmpty(existingFileGuid))
                    {
                        // Add as resource file (not source code) so it gets copied to bundle
                        fileGuid = project.AddFile("GoogleService-Info.plist", "GoogleService-Info.plist", PBXSourceTree.Source);
                        project.AddFileToBuild(targetGuid, fileGuid);
                    }
                    else
                    {
                        fileGuid = existingFileGuid;
                        // Ensure it's added to build (try adding even if it might already be there - AddFileToBuild handles duplicates)
                        project.AddFileToBuild(targetGuid, fileGuid);
                    }
                    
                    File.WriteAllText(projPath, project.WriteToString());
                    Debug.Log("[GoogleSignIn] Added GoogleService-Info.plist to Xcode project as resource");
                }
                else
                {
                    Debug.LogWarning("[GoogleSignIn] Xcode project file not found. GoogleService-Info.plist copied but may need manual addition to Xcode project.");
                }
            }
            else
            {
                Debug.LogError("[GoogleSignIn] GoogleService-Info.plist not found in Assets folder!");
            }

            // Create Podfile if it doesn't exist (fallback if EDM4U didn't generate it)
            string podfilePath = Path.Combine(path, "Podfile");
            if (!File.Exists(podfilePath))
            {
                string podfileContent = @"# Podfile for Google Sign-In iOS
# Generated by GoogleSignInPostProcess
# GoogleSignIn 9.0 requires iOS 12.0 minimum

platform :ios, '12.0'

# Set minimum deployment target for all pods
post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      if config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'].to_f < 12.0
        config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '12.0'
      end
    end
  end
end

# Only link pods to UnityFramework to avoid duplicate symbols
target 'UnityFramework' do
  # Google Sign-In SDK (Latest version 9.0.0)
  pod 'GoogleSignIn', '~> 9.0'
end

# Do NOT add pods to Unity-iPhone target to prevent duplicate class warnings
";
                File.WriteAllText(podfilePath, podfileContent);
                Debug.Log("[GoogleSignIn] Created Podfile in iOS build directory");
            }
            else
            {
                Debug.Log("[GoogleSignIn] Podfile already exists, skipping creation");
            }

            plist.WriteToFile(plistPath);
        }
    }
}
#endif
