using System;
using System.IO;
using UnityEditor;
using UnityEditor.Callbacks;
using UnityEditor.iOS.Xcode;
using UnityEngine;

namespace GoogleSignIn.Editor
{
    /// <summary>
    /// iOS: merges REVERSED_CLIENT_ID URL scheme and copies GoogleService-Info.plist from anywhere under Assets.
    /// </summary>
    public static class GoogleSignInPostProcess
    {
        [PostProcessBuild(1)]
        public static void OnPostProcessBuild(BuildTarget buildTarget, string path)
        {
            if (buildTarget != BuildTarget.iOS)
            {
                return;
            }

            string plistPath = Path.Combine(path, "Info.plist");
            PlistDocument plist = new PlistDocument();
            plist.ReadFromFile(plistPath);

            if (!TryFindGoogleServiceInfoPlist(out string googleServiceInfoSource, out string reversedClientId))
            {
                Debug.LogWarning(
                    "[GoogleSignIn] GoogleService-Info.plist not found under Assets. " +
                    "Add it from the Firebase Console to enable the iOS URL scheme and Google Sign-In configuration.");
            }
            else if (!string.IsNullOrEmpty(reversedClientId))
            {
                EnsureUrlScheme(plist, reversedClientId);
                Debug.Log($"[GoogleSignIn] Ensured URL scheme for REVERSED_CLIENT_ID: {reversedClientId}");
            }
            else
            {
                Debug.LogWarning(
                    "[GoogleSignIn] REVERSED_CLIENT_ID missing in GoogleService-Info.plist. URL scheme was not added.");
            }

            if (!string.IsNullOrEmpty(googleServiceInfoSource) && File.Exists(googleServiceInfoSource))
            {
                string destPlist = Path.Combine(path, "GoogleService-Info.plist");
                File.Copy(googleServiceInfoSource, destPlist, true);
                Debug.Log("[GoogleSignIn] Copied GoogleService-Info.plist to iOS build");

                string projPath = Path.Combine(path, "Unity-iPhone.xcodeproj", "project.pbxproj");
                if (File.Exists(projPath))
                {
                    PBXProject project = new PBXProject();
                    project.ReadFromString(File.ReadAllText(projPath));
                    string targetGuid = project.GetUnityMainTargetGuid();
                    string existingFileGuid = project.FindFileGuidByProjectPath("GoogleService-Info.plist");
                    string fileGuid;
                    if (string.IsNullOrEmpty(existingFileGuid))
                    {
                        fileGuid = project.AddFile("GoogleService-Info.plist", "GoogleService-Info.plist", PBXSourceTree.Source);
                        project.AddFileToBuild(targetGuid, fileGuid);
                    }
                    else
                    {
                        fileGuid = existingFileGuid;
                        project.AddFileToBuild(targetGuid, fileGuid);
                    }

                    File.WriteAllText(projPath, project.WriteToString());
                    Debug.Log("[GoogleSignIn] Registered GoogleService-Info.plist in the Xcode project");
                }
                else
                {
                    Debug.LogWarning("[GoogleSignIn] Xcode project file not found; add GoogleService-Info.plist manually if needed.");
                }
            }

            string podfilePath = Path.Combine(path, "Podfile");
            if (!File.Exists(podfilePath))
            {
                // Do not use a multiline verbatim string here: Unity's preprocessor treats lines starting with '#' as directives (CS1024).
                string podfileContent =
                    "# Podfile for Google Sign-In iOS\n" +
                    "# Generated by GoogleSignInPostProcess (fallback if EDM did not create a Podfile)\n" +
                    "\n" +
                    "platform :ios, '12.0'\n" +
                    "\n" +
                    "post_install do |installer|\n" +
                    "  installer.pods_project.targets.each do |target|\n" +
                    "    target.build_configurations.each do |config|\n" +
                    "      if config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'].to_f < 12.0\n" +
                    "        config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '12.0'\n" +
                    "      end\n" +
                    "    end\n" +
                    "  end\n" +
                    "end\n" +
                    "\n" +
                    "target 'UnityFramework' do\n" +
                    "  pod 'GoogleSignIn', '~> 9.0'\n" +
                    "end\n";

                File.WriteAllText(podfilePath, podfileContent);
                Debug.Log("[GoogleSignIn] Created Podfile in iOS build directory");
            }

            plist.WriteToFile(plistPath);
        }

        private static bool TryFindGoogleServiceInfoPlist(out string fullPath, out string reversedClientId)
        {
            fullPath = null;
            reversedClientId = null;

            foreach (string guid in AssetDatabase.FindAssets("GoogleService-Info"))
            {
                string assetPath = AssetDatabase.GUIDToAssetPath(guid);
                if (!assetPath.EndsWith("GoogleService-Info.plist", StringComparison.OrdinalIgnoreCase))
                {
                    continue;
                }

                string relative = assetPath.StartsWith("Assets/", StringComparison.Ordinal)
                    ? assetPath.Substring("Assets/".Length)
                    : assetPath;
                string candidate = Path.Combine(Application.dataPath, relative);
                if (!File.Exists(candidate))
                {
                    continue;
                }

                fullPath = candidate;
                try
                {
                    PlistDocument svc = new PlistDocument();
                    svc.ReadFromFile(candidate);
                    PlistElement el = svc.root["REVERSED_CLIENT_ID"];
                    if (el != null)
                    {
                        reversedClientId = el.AsString();
                    }
                }
                catch (Exception e)
                {
                    Debug.LogWarning($"[GoogleSignIn] Could not read REVERSED_CLIENT_ID from {assetPath}: {e.Message}");
                }

                return true;
            }

            return false;
        }

        private static void EnsureUrlScheme(PlistDocument plist, string reversedClientId)
        {
            PlistElementArray urlTypes;
            if (plist.root["CFBundleURLTypes"] != null)
            {
                urlTypes = plist.root["CFBundleURLTypes"].AsArray();
            }
            else
            {
                urlTypes = plist.root.CreateArray("CFBundleURLTypes");
            }

            foreach (PlistElement entry in urlTypes.values)
            {
                PlistElementDict dict = entry as PlistElementDict;
                if (dict == null)
                {
                    continue;
                }

                if (dict["CFBundleURLSchemes"] == null)
                {
                    continue;
                }

                foreach (PlistElement scheme in dict["CFBundleURLSchemes"].AsArray().values)
                {
                    if (string.Equals(scheme.AsString(), reversedClientId, StringComparison.Ordinal))
                    {
                        return;
                    }
                }
            }

            PlistElementDict urlType = urlTypes.AddDict();
            PlistElementArray urlSchemes = urlType.CreateArray("CFBundleURLSchemes");
            urlSchemes.AddString(reversedClientId);
        }
    }
}
